steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/augmented-atom-487000-j1/movie-agent', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/augmented-atom-487000-j1/movie-agent']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'movie-agent'
      - '--image=gcr.io/augmented-atom-487000-j1/movie-agent'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--port=8080'
