"""
Artifact tools — save analysis reports to disk.
"""

import json
import os
from datetime import datetime

from google.adk.tools import FunctionTool

_OUTPUTS_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "outputs")


def _save_report(
    question: str,
    hypothesis: str,
    evidence_bullets: str,
    movie_count: int,
    dataset_label: str,
) -> str:
    """Save a movie analysis report as a timestamped Markdown file.

    Args:
        question: The user's original question.
        hypothesis: The hypothesis paragraph.
        evidence_bullets: Supporting evidence bullet points (as a single string).
        movie_count: Number of movies analyzed.
        dataset_label: Label describing the dataset (e.g. "Horror 2004-2024", "Top Grossing").

    Returns:
        JSON string confirming the saved file path.
    """
    os.makedirs(_OUTPUTS_DIR, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"report_{ts}.md"
    filepath = os.path.join(_OUTPUTS_DIR, filename)

    content = f"""# Movie Analysis Report

**Generated**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Dataset**: {dataset_label} ({movie_count} movies)

## Question
{question}

## Hypothesis
{hypothesis}

## Supporting Evidence
{evidence_bullets}

---
*Generated by Movie Analysis Agent*
"""
    with open(filepath, "w") as f:
        f.write(content)

    return json.dumps({"status": "saved", "file": filename})


save_report = FunctionTool(func=_save_report)
